// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/lookup.proto

package lookup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AppLookup_Lookup_FullMethodName = "/lookup.AppLookup/Lookup"
)

// AppLookupClient is the client API for AppLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppLookupClient interface {
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
}

type appLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewAppLookupClient(cc grpc.ClientConnInterface) AppLookupClient {
	return &appLookupClient{cc}
}

func (c *appLookupClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, AppLookup_Lookup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppLookupServer is the server API for AppLookup service.
// All implementations must embed UnimplementedAppLookupServer
// for forward compatibility
type AppLookupServer interface {
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	mustEmbedUnimplementedAppLookupServer()
}

// UnimplementedAppLookupServer must be embedded to have forward compatible implementations.
type UnimplementedAppLookupServer struct {
}

func (UnimplementedAppLookupServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedAppLookupServer) mustEmbedUnimplementedAppLookupServer() {}

// UnsafeAppLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppLookupServer will
// result in compilation errors.
type UnsafeAppLookupServer interface {
	mustEmbedUnimplementedAppLookupServer()
}

func RegisterAppLookupServer(s grpc.ServiceRegistrar, srv AppLookupServer) {
	s.RegisterService(&AppLookup_ServiceDesc, srv)
}

func _AppLookup_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLookupServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLookup_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLookupServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppLookup_ServiceDesc is the grpc.ServiceDesc for AppLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lookup.AppLookup",
	HandlerType: (*AppLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _AppLookup_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lookup.proto",
}
