// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/lookup.proto

package lookup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey string `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lookup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExtraLogLabels []*LookupResponse_ExtraLogLabel     `protobuf:"bytes,2,rep,name=extraLogLabels,proto3" json:"extraLogLabels,omitempty"`
	CorsOrigins    []*LookupResponse_CORSAllowedOrigin `protobuf:"bytes,3,rep,name=corsOrigins,proto3" json:"corsOrigins,omitempty"`
	StackID        string                              `protobuf:"bytes,4,opt,name=stackID,proto3" json:"stackID,omitempty"`
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lookup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_proto_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookupResponse) GetExtraLogLabels() []*LookupResponse_ExtraLogLabel {
	if x != nil {
		return x.ExtraLogLabels
	}
	return nil
}

func (x *LookupResponse) GetCorsOrigins() []*LookupResponse_CORSAllowedOrigin {
	if x != nil {
		return x.CorsOrigins
	}
	return nil
}

func (x *LookupResponse) GetStackID() string {
	if x != nil {
		return x.StackID
	}
	return ""
}

type LookupResponse_ExtraLogLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LookupResponse_ExtraLogLabel) Reset() {
	*x = LookupResponse_ExtraLogLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lookup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupResponse_ExtraLogLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse_ExtraLogLabel) ProtoMessage() {}

func (x *LookupResponse_ExtraLogLabel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse_ExtraLogLabel.ProtoReflect.Descriptor instead.
func (*LookupResponse_ExtraLogLabel) Descriptor() ([]byte, []int) {
	return file_proto_lookup_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LookupResponse_ExtraLogLabel) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LookupResponse_ExtraLogLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LookupResponse_CORSAllowedOrigin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
}

func (x *LookupResponse_CORSAllowedOrigin) Reset() {
	*x = LookupResponse_CORSAllowedOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lookup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupResponse_CORSAllowedOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse_CORSAllowedOrigin) ProtoMessage() {}

func (x *LookupResponse_CORSAllowedOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lookup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse_CORSAllowedOrigin.ProtoReflect.Descriptor instead.
func (*LookupResponse_CORSAllowedOrigin) Descriptor() ([]byte, []int) {
	return file_proto_lookup_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LookupResponse_CORSAllowedOrigin) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_proto_lookup_proto protoreflect.FileDescriptor

var file_proto_lookup_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x22, 0x28, 0x0a, 0x0d,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x22, 0xc2, 0x02, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4c, 0x0a,
	0x0e, 0x65, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x6f, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x4c, 0x6f, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x0e, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x4c, 0x6f, 0x67, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x4a, 0x0a, 0x0b, 0x63,
	0x6f, 0x72, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x4f, 0x52, 0x53, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x73,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x63, 0x6b,
	0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x49,
	0x44, 0x1a, 0x3b, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x4c, 0x6f, 0x67, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x2b,
	0x0a, 0x11, 0x43, 0x4f, 0x52, 0x53, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x32, 0x46, 0x0a, 0x09, 0x41,
	0x70, 0x70, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x39, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x12, 0x15, 0x2e, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x65, 0x5a, 0x63, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x72, 0x61, 0x66, 0x61, 0x6e, 0x61, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x6f, 0x6d,
	0x6f, 0x70, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x2f, 0x66, 0x61, 0x72, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x2f, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_lookup_proto_rawDescOnce sync.Once
	file_proto_lookup_proto_rawDescData = file_proto_lookup_proto_rawDesc
)

func file_proto_lookup_proto_rawDescGZIP() []byte {
	file_proto_lookup_proto_rawDescOnce.Do(func() {
		file_proto_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lookup_proto_rawDescData)
	})
	return file_proto_lookup_proto_rawDescData
}

var file_proto_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_lookup_proto_goTypes = []interface{}{
	(*LookupRequest)(nil),                    // 0: lookup.LookupRequest
	(*LookupResponse)(nil),                   // 1: lookup.LookupResponse
	(*LookupResponse_ExtraLogLabel)(nil),     // 2: lookup.LookupResponse.ExtraLogLabel
	(*LookupResponse_CORSAllowedOrigin)(nil), // 3: lookup.LookupResponse.CORSAllowedOrigin
}
var file_proto_lookup_proto_depIdxs = []int32{
	2, // 0: lookup.LookupResponse.extraLogLabels:type_name -> lookup.LookupResponse.ExtraLogLabel
	3, // 1: lookup.LookupResponse.corsOrigins:type_name -> lookup.LookupResponse.CORSAllowedOrigin
	0, // 2: lookup.AppLookup.Lookup:input_type -> lookup.LookupRequest
	1, // 3: lookup.AppLookup.Lookup:output_type -> lookup.LookupResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_lookup_proto_init() }
func file_proto_lookup_proto_init() {
	if File_proto_lookup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lookup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lookup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lookup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupResponse_ExtraLogLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lookup_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupResponse_CORSAllowedOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lookup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lookup_proto_goTypes,
		DependencyIndexes: file_proto_lookup_proto_depIdxs,
		MessageInfos:      file_proto_lookup_proto_msgTypes,
	}.Build()
	File_proto_lookup_proto = out.File
	file_proto_lookup_proto_rawDesc = nil
	file_proto_lookup_proto_goTypes = nil
	file_proto_lookup_proto_depIdxs = nil
}
