extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

processors:

exporters:
  otlp:
    endpoint: otlp.example.com:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

  extensions: [health_check]
