---
depends_on: null
kind: pipeline
name: build distributions
steps:
- commands:
  - make generate-sources
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build distributions
  platform: {}
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for windows 386
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: "386"
    os: windows
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for windows amd64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: amd64
    os: windows
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for windows arm64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: arm64
    os: windows
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for windows ppc64le
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: ppc64le
    os: windows
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for linux 386
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: "386"
    os: linux
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for linux amd64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: amd64
    os: linux
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for linux arm64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: arm64
    os: linux
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for linux ppc64le
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: ppc64le
    os: linux
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for darwin 386
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: "386"
    os: darwin
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for darwin amd64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: amd64
    os: darwin
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for darwin arm64
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: arm64
    os: darwin
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
depends_on:
- build distributions
kind: pipeline
name: build binaries for darwin ppc64le
steps:
- commands:
  - go build -C ./distributions/otel-grafana/_build -ldflags="-s -w" -trimpath
  depends_on: []
  entrypoint: null
  environment: {}
  image: golang:1.20.4
  name: build binaries
  platform:
    arch: ppc64le
    os: darwin
  settings: {}
trigger:
  branch:
  - main
  event:
    include:
    - pull_request
    - push
type: docker
---
get:
  name: .dockerconfigjson
  path: secret/data/common/gcr
kind: secret
name: dockerconfigjson
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: gh_token
---
get:
  name: service-account
  path: infra/data/ci/gcr-admin
kind: secret
name: gcr_admin
---
get:
  name: token
  path: infra/data/ci/argo-workflows/trigger-service-account
kind: secret
name: argo_token
---
kind: signature
hmac: 634de6044011d3acfe45e92d9f6703c278ee321601a6ccd0d224f918efdd636e

...
