name: Auto-update

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Auto-update on new core/contrib versions
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Auto-update
        run: ./scripts/update-to-latest-otelcol.sh -c
