name: Release tracing

on:
  release:
    types: [published]

jobs:
  release:
    name: Release tracing
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: tracing
    secrets: inherit
    permissions: write-all