name: Release delta-to-cumulative

on:
  release:
    types: [published]

jobs:
  release:
    name: Release delta-to-cumulative
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: delta-to-cumulative
    secrets: inherit
    permissions: write-all
